name: fluom
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'



#---------------------- PACKAGE ----------------------#

dependencies:
  flutter:
    sdk: flutter

# Utility Package
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.7
  lottie: ^2.7.0
  connectivity_plus: ^5.0.2


# Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8



# State Management
  get: ^4.6.6
  google_fonts: ^6.1.0
  get_storage: ^2.1.1



# Product Specific

  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1

# firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.6
  firebase_storage: ^11.6.0
  cached_network_image: ^3.3.1
# Payment-Gateway-RazorPay
  fluttertoast: ^8.2.5
  razorpay_flutter: ^1.3.7
# Payment-Gateway-Stripe
  flutter_stripe: ^10.1.1
  rxdart: ^0.27.7
  async: ^2.11.0
  uuid: ^4.4.0




#---------------------- ./ PACKAGE END ----------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true



#---------------------- LOCAL ASSETS ----------------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/login_screen_images/
    - assets/images/email_verification/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/store_icons/
    - assets/images/store_icons/vertical_icons_home/
    - assets/images/profile/
    - assets/images/rating_reviews/
    - assets/images/payment_method/
    - assets/animations/
    - assets/TAllimage/
    - assets/TAllimage/icons/categories/
    - assets/TAllimage/banners/


    #---------------------- LOCAL FONTS ----------------------#
