// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtmDiYv3Q5FgtNN0C6f6fBIEfN_kNHZf4',
    appId: '1:652403237117:web:425b24736b73a229ef9e94',
    messagingSenderId: '652403237117',
    projectId: 'fluom-s-store',
    authDomain: 'fluom-s-store.firebaseapp.com',
    storageBucket: 'fluom-s-store.appspot.com',
    measurementId: 'G-62K67R4LF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKo6xINglNWSC583PCf-AWZbbuU__LuMs',
    appId: '1:652403237117:android:4adf6eaab9534da7ef9e94',
    messagingSenderId: '652403237117',
    projectId: 'fluom-s-store',
    storageBucket: 'fluom-s-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPoh9U44rKX5ZtjyB7IMt5J-qtvrwggr4',
    appId: '1:652403237117:ios:e5bdd4e753a59b32ef9e94',
    messagingSenderId: '652403237117',
    projectId: 'fluom-s-store',
    storageBucket: 'fluom-s-store.appspot.com',
    androidClientId: '652403237117-bf34gevb5usdra5q06irt2a29s5ssfqu.apps.googleusercontent.com',
    iosClientId: '652403237117-rtb3qvqb9tmsnn95psfbnjm5d0go119r.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPoh9U44rKX5ZtjyB7IMt5J-qtvrwggr4',
    appId: '1:652403237117:ios:0c171fd77324f5b0ef9e94',
    messagingSenderId: '652403237117',
    projectId: 'fluom-s-store',
    storageBucket: 'fluom-s-store.appspot.com',
    androidClientId: '652403237117-bf34gevb5usdra5q06irt2a29s5ssfqu.apps.googleusercontent.com',
    iosClientId: '652403237117-kl8iq8ph9ifdnu7a6benovtgrra51595.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluom.RunnerTests',
  );
}
